services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fcgUserServiceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fcg-user-service:
    container_name: fcg-user-service
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=fcgUserServiceDb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
